### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by Russlyman** [Ge0rg3/flask-parameter-validation#21]
Hi there,

It appears this module has a dependency on python-dateutil that isn’t satisfied when installing flask-parameter-validation through pip. Installing the dependency manually solves this problem.

`Traceback (most recent call last):
  File "XXXX\venv\lib\site-packages\flask\cli.py", line 219, in locate_app
    __import__(module_name)
  File "XXXX\app.py", line 10, in <module>
    from flask_parameter_validation import ValidateParameters, Route, Json, Query
  File "XXXX\venv\lib\site-packages\flask_parameter_validation\__init__.py", line 1, in <module>
    from .parameter_validation import ValidateParameters  # noqa: F401
  File "XXXX\venv\lib\site-packages\flask_parameter_validation\parameter_validation.py", line 10, in <module>
    from .parameter_types import File, Form, Json, Query, Route
  File "XXXX\venv\lib\site-packages\flask_parameter_validation\parameter_types\__init__.py", line 1, in <module>
    from .file import File
  File "XXXX\venv\lib\site-packages\flask_parameter_validation\parameter_types\file.py", line 6, in <module>
    from .parameter import Parameter
  File "XXXX\venv\lib\site-packages\flask_parameter_validation\parameter_types\parameter.py", line 7, in <module>
    import dateutil.parser as parser
ModuleNotFoundError: No module named 'dateutil'`

**Comment by Ge0rg3** [comment]
Great spot @Russlyman, just patched in the new version, many thanks!
